Added PUT request method and DELETE request method functionality
TechNumber/Mirea2021 pull request #2
Opened 2021-12-30 18:33 UTC by TechNumber

Added PUT request method and DELETE request method functionality to RequestController and RequestService

2021-12-30 18:51 UTC, Soagshka requested changes

2021-12-30 18:51 UTC, Soagshka commented on src/main/java/com/mirea/demo/controller/RequestController.java
> +        return DemoResponse.ok(requestService.putRequest(id, newRequestDTO));
Получение что-то не очень звучит
Лучше что-то вроде по идентификатору запроса изменияем данные и т.д.

2021-12-30 18:51 UTC, Soagshka commented on src/main/java/com/mirea/demo/service/RequestService.java
> +    }
В методе delete не нужно ничего возвращать, достаточно чего-то информативного, например, сообщения что данные удалены

2021-12-30 18:51 UTC, Soagshka commented on src/main/java/com/mirea/demo/service/RequestService.java
> +        requestEntity.setDescription(newRequestDTO.getDescription());
Для этого есть мапперы, не нужно вручную поля проставлять, а если их будет 100-200?
+ название DTO неудачное, оно же нужно для изменения

2021-12-30 19:15 UTC, Soagshka requested changes

2021-12-30 19:15 UTC, Soagshka commented on src/main/java/com/mirea/demo/controller/RequestController.java
>              notes = "Получение идентификатора запроса и его удаление из БД с возвратом тела запроса")
Тут бы тоже поменять

2021-12-30 19:15 UTC, Soagshka commented on src/main/java/com/mirea/demo/controller/RequestController.java
>      }
Зачем string в ответе?
У нас же есть DemoResponse с пустым ответом как раз для таких случаев

2021-12-30 19:15 UTC, Soagshka commented on src/main/java/com/mirea/demo/service/RequestService.java
>      }
Собственно и здесь не надо ничего возвращать

2021-12-30 19:15 UTC, Soagshka commented on src/main/java/com/mirea/demo/service/RequestService.java
>          return requestMapper.entityToDTO(requestEntity);
Саму DTO тоже отдельную сделать, можешь через наследование сделать

Возвращать нужно то, что сохранилось в базу

2021-12-30 20:44 UTC, TechNumber commented on src/main/java/com/mirea/demo/service/RequestService.java
>          return requestMapper.entityToDTO(requestEntity);
Наследование сделать пока не получилось, потому что возникают проблемы с Builder (в генерируемом RequestMapperImpl поля инициализируются через Builder, маппер пытается напрямую обратиться к закрытым полям, наследованным от родителя
![g3w40g8hbi](https://user-images.githubusercontent.com/95917281/147786817-3a2fd273-e242-49e0-b0ff-26f966f5b0ff.PNG)

2022-01-27 18:12 UTC, Soagshka commented on src/main/java/com/mirea/demo/service/RequestService.java
> +        return requestMapper.entityToDTO(requestRepository.findById(id).orElseThrow(() -> new RequestNotFoundException(id)));
Зачем это? У нас же уже есть requestEntity, не надо его заново получать по идентификатору

2022-01-27 18:12 UTC, Soagshka approved these changes

2022-01-28 08:22 UTC, merged